#!/bin/bash
#
# This is a basic installation program for the 'shutdown watcher program
# It is assumed the source/build files are below the current directory
#
BINDIR=/usr/local/bin/
MANPAGES=/usr/share/man/man1
SYSTEMD=/etc/systemd/system/

# Copy the man page and update the database
echo "installing man page"
cp ShutdownWatcher.1 ${MANPAGES}
mandb -q
echo "Installing binary and systemd control file"
# Copy the binary
cp build/ShutdownWatcher ${BINDIR}
# Copy the systemd config file
cp ShutdownWatcher.sevice ${SYSTEMD}
echo "Install complete"
