#!/bin/bash
#
# This is a basic installation program for the 'shutdown watcher program
# It is assumed the source/build files are below the current directory
#
BINDIR=/usr/local/bin/
MANPAGES=/usr/share/man/man1
#SYSTEMD=/etc/init.d
SYSTEMD=/etc/systemd/system

if [ ! -d testdir ]; then
    echo "This script MUST be run from the 'shutdownWatcher' program directory"
    exit 1
fi

cmake . && make
if [ $? -ne 0 ]; then
    echo "Bad return from build. Install aborted."
fi

# Copy the man page and update the database
echo "installing man page"
cp shutdownwatcher.1 ${MANPAGES}
mandb -q

echo "Installing binary"
# Copy the binary
cp shutdownwatcher ${BINDIR}

# Copy the /etc/default/shutdown file
cp shutdownwatcher_cfg_sample /etc/default/shutdown

# Copy the systemd config file
echo installing system control files
cp shutdownwatcher.service ${SYSTEMD}/

cp shutdownwatcher.99 /etc/init.d/shutdownwatcher
sudo systemctl daemon-reload
# update-rc.d shutdownwatcher  defaults
# update-rc.d shutdownwatcher  defaults-disabled
systemctl enable shutdownwatcher.service
echo "Install complete"
