#!/bin/bash
#
# This is a basic installation program for the 'shutdown watcher program
# It is assumed the source/build files are below the current directory
#
BINDIR=/usr/local/bin/
MANPAGES=/usr/share/man/man1
SYSTEMD=/etc/systemd/system

# remove command, ignore errors, force if directory.
RM='rm -rf'

# STOP the service

systemctl disable shutdownwatcher.service
systemctl stop    shutdownwatcher.service
${RM} ${SYSTEMD}/Shutdownwatcher.service

# Copy the man page
if [ -f ${MANPAGES}/shutdownwatcher.1 ]; then
echo "Removing man page"
${RM} ${MANPAGES}/shutdownwatcher.1
mandb -q
else
echo "Man pages Already deleted"
fi
# Remove the /etc/default/shutdown file
${RM} /etc/default/shutdown

# remove the binary
echo "Removing binary and service file"
${RM} ${BINDIR}shutdownwatcher


