#!/bin/bash
#
# This is a basic installation program for the 'shutdown watcher program
# It is assumed the source/build files are below the current directory
#
BINDIR=/usr/local/bin/
MANPAGES=/usr/share/man/man1
SYSTEMD=/etc/systemd/system/
RM='rm -rf'

# Copy the man page
if [ -f ${MANPAGES}/ShutdownWatcher.1 ]; then

echo "Removing man page"
${RM} ${MANPAGES}/ShutdownWatcher.1
mandb -q
else
echo "Man pages Already deleted"
fi

# remove the binary
echo "Removing binary and service file"
${RM} ${BINDIR}ShutdownWatcher
# remove the systemd config file
${RM} ${SYSTEMD}/ShutdownWatcher.service
echo "uninstall complete"

